version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
        description: raw yellow taxi data
        columns:
          - name: VendorID
            description: int indication trip provider
            data_type: integer
            meta:
              pii: false
              ownership: data_team
      - name: green_tripdata

